sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 53306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tSPKee8xgYhtQQ8hyaG
    access-key-secret: J5Sw47Sb6yznZ9ghfDlzPhAyHSmnz0
    bucket-name: sky-take-out-rime
  redis:
    host: localhost
    port: 56379
    database: 10
#  wechat: # 配置微信支付相关功能
#    appid:
#    secret:
#    mchid:
#    mch-serial-no:
#    private-key-file-path:
#    api-v3-key:
#    we-chat-pay-cert-file-path:
#    notify-url:
#    refund-notify-url:




